### ISSUE TITLE
Insert Div in Compose Body

### ISSUE THREAD

**Issue by Reakzy** [KartikTalwar/gmail.js#469] opened 2018-05-03 12:57 UTC
Hello,

I saw multiples issues on how to insert in compose Body like :
`gmail.observe.on('compose', function (compose, type) {
 window.setTimeout( function() {
     compose.body("<div>Test</div>");
    },0);
}`

But this exemple destroy everything in body. 
Is it possible to add at the end or anywhere in the body without destroy the text already in the body?

Thanks for your help !

**Comment by josteink** [comment] 2018-05-03 13:08
Obtain body first by calling `compose.body()` and append to that?

**Comment by Reakzy** [comment] 2018-05-03 13:44
i have :  `var composeBody = compose.$el;` to get the whole body, but how can i get the div of the Message Body with that?

**Comment by josteink** [comment] 2018-05-04 07:35
I think you misunderstood. `compose.body()` will give you the body-text of the email.

So you can do stuff like `compose.body(compose.body() + "<div>Some other stuff</div>");`

But if all you want to do is append a div, I think going for straight DOM-manipulation might be better:

````javascript
var div = getDiv();
var $bodyEl = compse.find("body"); // jQuery-object for body-element
bodyEl.append(div);
````

I haven't tested this code,  so it may not work exactly like that, but you get get the general idea.

**Comment by Reakzy** [comment] 2018-05-04 07:47
Oh yes, i did `compose.body(compose.body() + "<div>Some other stuff</div>");` and it work
Thank you !

**Comment by josteink** [comment] 2018-05-04 07:50
Not a bug. And problem solved. Closing.

**Closed by josteink** 2018-05-04 07:50 UTC
