### ISSUE TITLE
send_message event stopped working

### ISSUE THREAD

**Issue by huksley** [KartikTalwar/gmail.js#722] opened 2022-09-12 15:50 UTC
It is still something to be confirmed, but I can see that both `send_message` and `send_scheduled_message` does not work anymore.

These hooks are now never triggered:
```
this.gmail.observe.before("send_message", (url: string, body: string, data: Mail) => {});
this.gmail.observe.before("send_scheduled_message", (url: string, _body: string, data: Mail) => {});
```

### Browser differences

- Works fine in Firefox
- Does not work in Chrome (with the same Google account)

I can see there is different parameters passed in URL - Chrome v105

<img width="461" alt="image" src="https://user-images.githubusercontent.com/1594349/189690934-fc61f8e5-8a08-4efb-9dac-92f005f4b30e.png">

Firefox v104
<img width="568" alt="image" src="https://user-images.githubusercontent.com/1594349/189693293-2c2e36ae-5877-4532-8e63-1fb85a3299f2.png">

I am trying to investigate if it is payload or something...

**Comment by huksley** [comment] 2022-09-12 16:38
I can see the payloads send in Chrome vs Firefox are different

<img width="1280" alt="image" src="https://user-images.githubusercontent.com/1594349/189703377-fbd683fc-d2eb-483f-9220-6568b37aaaa7.png">

**Comment by MykhailoDev** [comment] 2022-09-12 17:20
have same problem

**Comment by josteink** [comment] 2022-09-12 20:22
This may be a duplicate of https://github.com/KartikTalwar/gmail.js/issues/721

Line format for XHR seems to have changed slightly.

**Comment by huksley** [comment] 2022-09-13 07:36
I decoded payload of msg I think it looks different from #721, not sure?

```typescript
interface RequestBodyMail {
  0: string; // messageId,
  1: PayloadAddress; // from
  2: PayloadAddress[]; // to
  3: PayloadAddress[]; // cc
  4: PayloadAddress[]; // bcc
  6: number; // timestamp
  7: string; // subject
  8?: {
    1?: {
      0: number;
      1: string; // body piece
    }[];
  }; // body structure
  10: string[]; // smart labels
}
```

**Comment by josteink** [comment] 2022-09-13 07:40
@huksley : If you can create a PR for the event-stuff, I'll be happy to review that and create another release.

I must admit that when it comes to the events themselves, I don't feel that confident in the parsing code as the email-parser (which I pretty much wrote from scratch myself).

**Comment by MykhailoDev** [comment] 2022-09-13 11:28
@huksley are you trying to solve the problem?

**Comment by huksley** [comment] 2022-09-13 12:04
Fixed, but need to have both code paths tested - I can't because my Firefox also started working with new APIs

**Comment by josteink** [comment] 2022-09-13 12:25
Not seeing this feedback, I've created a patch which I think fixes this issue. That is now published as `v1.1.2` on npmjs.

If you still think there's more work which needs to be done, please do let me know :smile:

**Comment by MykhailoDev** [comment] 2022-09-13 12:35
@josteink perfect, it work!

**Comment by huksley** [comment] 2022-09-13 12:45
Some users reports that older algorithm is back and older version of my extension works fine...

**Comment by huksley** [comment] 2022-09-13 12:48
@josteink I see you've made your own changes, btw these might now work:

            const sent_email_content_html = api.tools.parse_sent_message_html_payload(sent_email);
            const sent_attachments = api.tools.parse_sent_message_attachments(sent_email["11"]);

Because HTML payload format and attachments in a different format now.

**Comment by josteink** [comment] 2022-09-13 12:57
> Some users reports that older algorithm is back and older version of my extension works fine...  

Google please make up your mind 😮

**Comment by huksley** [comment] 2022-09-13 12:58
I think it is a rollout algorithm or something..

**Comment by josteink** [comment] 2022-09-13 12:58
> @josteink I see you've made your own changes, btw these might now work:
> 
> 
> 
>             const sent_email_content_html = api.tools.parse_sent_message_html_payload(sent_email);
> 
>             const sent_attachments = api.tools.parse_sent_message_attachments(sent_email["11"]);
> 
> 
> 
> Because HTML payload format and attachments in a different format now.

Do you mean may NOT work?

If so, PRs for getting them fixed are welcome 😉

**Comment by huksley** [comment] 2022-09-13 12:58
https://github.com/KartikTalwar/gmail.js/issues/722

**Closed** 2022-09-13 13:29 UTC
Labels: bug

**Comment by josteink** [comment] 2022-09-13 13:31
Released v1.1.3 with @huksley's fixes too.

**Comment by josteink** [comment] 2022-09-13 16:15
Only for new formats.

**Comment by huksley** [comment] 2022-09-13 18:08
I would think we need to support both versions for now.

**Comment by josteink** [comment] 2022-09-13 19:50
Then we should probably introduce some parser class/interface to do the parsing to clean up the code somewhat. 

Something like this?

    canParse(json) => boolean;
    parse(json) => array;

The code we have now is starting to have a somewhat desperate need for at least a minimal amount of architecture. 

As for both versions… are you talking about the events only? Or also the data APIs?

**Comment by huksley** [comment] 2022-09-13 20:06
I added the `is_email_new()` condition, and it triggers old and new parser as needed. But since older code also checks now for new email format, it probably will not work with older APIs...

> Then we should probably introduce some parser class/interface to do the parsing to clean up the code somewhat.

I would think there should be a parsers (or handlers) for different functionality of Gmail, versioned.
And users can provide flags which enable (or disable specific handlers) - this will be perfect for MW3 and future versions.

```typescript
interface GmailHandler {
   enable(gmail: GmailJS): void
} 

// Parses properly when you press Send in compose window (new format of send payloads)
class GmailSendPayloadHandler20220913 extends GmailHandler {
}

enabled = ["GmailNewHandler"]
handlers = [new GmailNewHandler(), new GmailSendPayloadHandler20220913()].filter(h => enabled.includes(h.constructor.name)
handlers.forEach(handler => handler.enable(this))
```

**Comment by onestep** [comment] 2022-09-24 21:51
Hello! It seems that `parse_sent_message_payload` is fixed as well now, and `parse_sent_message_payload_new` has incorrect `subject` field index (should be 7, but there is 8).

I believe that `parse_sent_message_payload_new` could be removed in favor of recently updated `parse_sent_message_payload`.
