### ISSUE TITLE
Gmail.js not working with "LinkedIn Sales Navigato"

### ISSUE THREAD

**Issue by shaharpan** [KartikTalwar/gmail.js#316] opened 2016-10-03 19:05 UTC
When I have my plugin installed with LinkedIn Sales Navigator. Gmail keeps crashing. Can not send emails. 
Any idea where I might be looking?

**Comment by KartikTalwar** [comment] 2016-10-03 19:58
which observers are you using? can you share your load script

**Comment by shaharpan** [comment] 2016-10-03 20:01
I am using 1) On_compose 2) undo_send 3) before_send 4) after_send. 5) recipient_change

**Comment by shaharpan** [comment] 2016-10-03 20:21
If this helps: Error in console by Sales Navigator is: 
" ERROR: required DOM elements not found in Gmail. TypeError: Cannot read property 'getAttribute' of undefined(…) "

**Comment by shaharpan** [comment] 2016-10-06 06:59
@KartikTalwar

**Comment by shaharpan** [comment] 2016-10-09 14:00
@JerryBels : Can you help please?

**Comment by JerryBels** [comment] 2016-10-09 17:18
@shaharpan I added the extension but don't have any problem to send emails. I'm using `on compose`, `undo send`, `before send_message` and `after send_message` as well. Not `recipient_change` though.

My guess from your error message is that this extension adds some DOM elements, and one or more of your manipulations changes the way the DOM behave, thus making this extension fail in its checks.

are you able to locate what is the source of that error using the console ? Any error from your own extension ? Anything in gmail.js ? Otherwise no one would be able to help you, I think, and you will have to [create a mcve](http://stackoverflow.com/help/mcve)

**Comment by shaharpan** [comment] 2016-10-09 17:22
Even if I remove all code from main.js and try to load my plugin and sales navigator. It gives same error. 
PS: I have not update gmail.js from last 3-4 months.

**Comment by JerryBels** [comment] 2016-10-09 17:54
Well, buddy, if you didn't update gmail.js... undo send won't work ! I added this not long ago. Areyou sure the error comes from the linkedin plugin ? Anyway, you should update gmail.js.

**Comment by shaharpan** [comment] 2016-10-09 17:59
Yup I am sure. As in console error originates from linkedin's js. Also undo send I had updated long back same way only. So its working for me. 
I have added many functions in gmail.js other than the provided one. 
![sales_error](https://cloud.githubusercontent.com/assets/14907693/19222529/40057be6-8e78-11e6-9419-96e0ad5b2ab3.PNG)

**Comment by JerryBels** [comment] 2016-10-09 18:08
Okay, I guess you still need to implement recent updates to gmail.js. Even for stability it's much better. Now, about your problem, I opened that .js [on linkedin's server](https://www.linkedin.com/sales/assets/%2Flighthouse-frontend%2Fconcat%2Flfg-plugin-v2_en_US.js) and I seem unable to understand what the problem is. Looks like your code changes the DOM, as I said, because the selector in question seems ok to me, so I don't see any other possibility. Maybe someone else will be able to help you more. Good luck ! Come back to tell us if you do find something.

**Comment by shaharpan** [comment] 2016-10-12 19:40
@JerryBels Sorry to bother you again. 
So I have updated gmail.js to latest build. Now sales navigator loads with gmail.js on inbox page. But all the events like "On compose" gives error for sales navigator. "Can not get id of undefined." I guess compose object is not getting captured. I have applied fix for #284 separately also.

**Comment by JerryBels** [comment] 2016-10-13 08:55
I know Sales Navigator does this, but I had no issue at all adding a button to the compose window (I do this also). My plugin works with Sales Navigator flawlessly. I'm really not sure what I could do to help you more. I still encourage you to get rid of all your code and add it pieces by pieces, starting with the mandatory, to get a mcve.

**Comment by shaharpan** [comment] 2016-10-18 16:38
@JerryBels : After updating the gmail.js it worked. I was trying to solve errors generated by sales navigator which are anyways coming without any plugin. So I think those can be ignored.
Now I am facing new issue. "on compose" works well but "before send" or "after send" is not firing. 
#193

**Comment by shaharpan** [comment] 2016-11-03 12:58
@KartikTalwar Can you help. Before send or after send not working for me.

**Comment by josteink** [comment] 2017-02-10 19:45
> After updating the gmail.js it worked.

Based on this, and this being an old report, I'm closing this issue.

> Can you help. Before send or after send not working for me.

Please open new issues (or search for exising!) specifically for this if you still have issues.

**Closed by josteink** 2017-02-10 19:45 UTC
