### ISSUE TITLE
Geting email data as empty

### ISSUE THREAD

**Issue by getzvnm** [KartikTalwar/gmail.js#507] opened 2018-07-30 04:09 UTC
Hi,
am added the below code to get email data and it works. but when i sent a message and view thread from 'view mwssage' option it returns empty data
The gmail url in this case is `https://mail.google.com/mail/u/0/#sent/undefined`

```
gmail.observe.on("view_thread", function(obj) {
  window.setTimeout( function() {
    var emails = gmail.get.email_data();
    console.log(emails); 
  }, 0);
});
```
is there any solution to get the email data?

![viewmessg](https://user-images.githubusercontent.com/37620550/43377156-caa66056-93dc-11e8-99f1-0ef86a46ca86.png)

**Comment by josteink** [comment] 2018-07-30 12:44
Can reproduce. Not sure what a good workaround is.

**Comment by josteink** [comment] 2018-07-30 12:48
Looking at your code, the problem seems to be that this is triggered with the `view_thread` event.

It seems Google has changed some bits, so that the thread and emails are rendered seperately.

`gmail.get.email_data()` internally uses `gmail.get.email_id()` when no ID is provided (like in your example), and this again depends on the email being rendered. At the time of `view_thread` it is not.

If you increase the time-out or make your event-handler depend on `view_email` instead, this might work?

Hope you can get it working!

In the meantime, I'm closing this issue, as it's not a library-issue, but a problem with how it is used.

**Closed** 2018-07-30 12:49 UTC
Labels: invalid
