### ISSUE TITLE
window.opener explodes

### ISSUE THREAD

**Issue by revmischa** [KartikTalwar/gmail.js#368] opened 2017-01-16 23:11 UTC
```
      typeof(window) !== "undefined" && window.opener !== null && typeof window.opener.GLOBALS !== "undefined"
          ? window.opener.GLOBALS
```

This code blows up if you open gmail from a link on another domain with a cross-origin request denied error.

**Comment by josteink** [comment] 2017-01-20 07:12
Sorry about the late response.

While I'm sure what you say are true, I'm curious about what use-case we are talking about here. What kind of useful interaction against gmail is it which fails due to this specific code?

Can you outline in greater detail a testable scenario we can look into?

**Comment by revmischa** [comment] 2017-01-22 17:51
Adding a "send via gmail" button to another page, having someone click it and be brought to gmail compose window. Just add a link that goes to gmail from another domain and click it.

**Comment by josteink** [comment] 2017-01-23 06:20
I've created a page like this:

````html
<html>
  <body>
    <a href="http://mail.google.com/">Same window</a>
    <a href="http://mail.google.com/" target="new">New window</a>
  </body>
</html>
````

Using this code is not enough for me to reproduce, but I'm using NodeJS-style loading using `require` and bundling.

Have you tried that? If not, could you try that?

**Comment by ascra** [comment] 2017-01-23 07:36
@josteink Try navigating to Gmail using `window.open([ ... ])` after a click event

**Comment by josteink** [comment] 2017-01-25 19:57
Oh I understand what you mean now. Sorry about being slow.  I'm not sure why this happens though: this part of the code clearly probes the *current* window before checking its opener:

https://github.com/KartikTalwar/gmail.js/blob/master/src/gmail.js#L41-L46

I really can't see any reason for this to fail, if loading gmail in a regular tab doesn't.

I'll try to reproduce the error condition and if so, see if there's any viable workaround.

**Comment by revmischa** [comment] 2017-01-25 21:04
Because the _opener_ of the _current window_ is a different origin.

**Comment by josteink** [comment] 2017-01-26 11:36
I'm sorry.

If you re-read my reply, you'll see that I cannot reproduce it and I cannot understand why it happens:

* My code to reproduce is hosted on a different domain, so that alone does not seem to be enough.
* `window.GLOBALS` is probed long before `window.opener.GLOBALS`, so whatever `window.opener` is and what origin it has really shouldn't matter.
* And as I've now asked several times: How do you load Gmail.js? Do you add a script-tag and probe for it to complete, or do you use NodeJS-style `require()` statements in your code?

Can you produce *more complete* code-samples to reproduce? Maybe a complete POC github repo?

**Comment by josteink** [comment] 2017-02-10 19:39
Is this still an issue for you? If so, can you provide some feedback to my questions?

If I receive no feedback on this issue in the near future, I will assume it's no longer something which needs to be resolved, and will close it.

**Comment by ascra** [comment] 2017-02-13 15:05
We are loading gmail.js in a Chrome extension. I'll see if we can provide a complete example.

**Comment by revmischa** [comment] 2017-08-11 10:21
@josteink we're using webpack to compile everything down into a single JS file that's loaded as a background script in a chrome extension.

**Comment by josteink** [comment] 2017-08-11 10:31
Can you provide a sample repo which demonstrates the problem consistently?

Basically something like one of the existing boilerplate-repos?

**Comment by josteink** [comment] 2017-09-24 10:23
Closing issue due to lack of activity. Please reopen if needed.

**Closed by josteink** 2017-09-24 10:23 UTC
Labels: bug

**Comment by josteink** [comment] 2019-02-01 14:50
There’s a bit of context I need to regain here, not to mention issues with understanding the scope of the change. 

I’ll try to take a look at it Monday, but if you want to outline *why* you are changing what you do and in what ways it helps prevent this error in the meantime, it will probably help me getting this reviewed a bit more quickly.

**Comment by onestep** [comment] 2019-02-05 15:13
@josteink, short answer - I've added an access check for `window.opener`, and if it fails gmail.js won't try to access it again. This prevents failures on initialization phase.
Now with more context - you can open Gmail from some other page, i.e. from [G Suite hub](https://apps.google.com/user/hub). In this case, you'll have `window.opener` from another origin, and when you try to read some properties from it, you'll have an error because of security restrictions. The point of my fix is to determine, if we can access `window.opener`, and use it only in this case.

**Comment by josteink** [comment] 2019-02-08 10:48
Sorry about the slow response. Been down with a flue.

>  I've added an access check for `window.opener`, and if it fails gmail.js won't try to access it again. This prevents failures on initialization phase.

I guess this is fair enough and the simplest part of the fix to understand. What I find harder is following the chain of its consequences this simple chain leads to.

> Now with more context - you can open Gmail from some other page, i.e. from [G Suite hub](https://apps.google.com/user/hub). In this case, you'll have `window.opener` from another origin, and when you try to read some properties from it, you'll have an error because of security restrictions.

This is where I'm not so sure about what the right approach is. If we can't access `window.opener` from these contexts, there's a lot of stuff GmailJS wants to do which it can't do. To me. it seems like blowing up is the right thing to do!

What part of GmailJS are you using in these contexts, and do they actually work with your fix? That is... Are you actually fixing bugs, or are you moving them from initialization to invocation?

Any help to understand this use-case is greatly appreciated.

**Comment by onestep** [comment] 2019-02-12 07:22
> If we can't access `window.opener` from these contexts, there's a lot of stuff GmailJS wants to do which it can't do. To me. it seems like blowing up is the right thing to do!
I can't agree here. Access to `window.opener` is important when you pop out the message window - in this case we need to know the opener context to access "root" Gmail window. But if you came to root Gmail window from third-party resource, there's nothing useful (at least for gmail.js :)) you can get from its context.
> What part of GmailJS are you using in these contexts, and do they actually work with your fix?
I am using `get` functions, they rely on XHR interceptor, which gets set up in `api.tools.xhr_watcher`, which tries to determine root window by looking for `window.opener` context data.
> Are you actually fixing bugs, or are you moving them from initialization to invocation?
There's actually nothing we can fix, just because access to foreign window context is denied by browser security rules, and I think it's the right thing. We can handle this situation though, that's what I suggest in my draft change.
I can update the code to make the logic and variable naming more clear, if needed.

**Comment by josteink** [comment] 2019-05-16 09:27
> I can't agree here. Access to window.opener is important when you pop out the message window - in this case we need to know the opener context to access "root" Gmail window. But if you came to root Gmail window from third-party resource, there's nothing useful (at least for gmail.js :)) you can get from its context.

Ok. I get the difference now.

And I do agree: This should be fixed.
