### ISSUE TITLE
gmail.get.user_email() returns null

### ISSUE THREAD

**Issue by uri3000** [KartikTalwar/gmail.js#748] opened 2023-02-24 00:39 UTC
This is my code, taken directly from the boilerplate:
```

const GmailFactory = require('gmail-js');
const jQuery = require("jquery");

console.log('loading something...');

window._gmailjs = window._gmailjs || new GmailFactory.Gmail(jQuery);

const loaderId = setInterval(() => {
    console.log('test');
    if (!window._gmailjs) {
        return;
    }

    clearInterval(loaderId);
    startExtension(window._gmailjs);
}, 100);

// actual extension-code
function startExtension(gmail) {
    console.log("Extension loading...");
    window.gmail = gmail;

    gmail.observe.on("load", () => {
        const userEmail = gmail.get.user_email();
        console.log("Hello, " + userEmail + ". This is your extension talking!");

        gmail.observe.on("view_email", (domEmail) => {
            console.log("Looking at email:", domEmail);
            const emailData = gmail.new.get.email_data(domEmail);
            console.log("Email data:", emailData);
        });

        gmail.observe.on("compose", (compose) => {
            console.log("New compose window is opened!", compose);
        });
    });
}
```

It is set up in the content script but returns null in console output:
<img width="373" alt="image" src="https://user-images.githubusercontent.com/7873124/221063540-91ba23d1-3cfd-4f7e-a357-4b2fae967434.png">

Any help would be appreciated

**Comment by josteink** [comment] 2023-02-27 07:44
Using the boilerplate and latest gmail.js, I've tested on three different google accounts, using Google Chrome, on Linux:

* gmail.com
* a grandfathered free google apps account
* and a "regular" paid google work account

On neither of those accounts can I reproduce this issue.

If this is an issue to you, you will probably have to do the debugging yourself, and try to reverse engineer another way to obtain the email and create a PR for it.

There's not really much I can do on my end.

**Comment by josteink** [comment] 2023-02-27 07:45
Also: This issue is a duplicate of https://github.com/KartikTalwar/gmail.js/issues/734.

Closing this one, so the oldest one with most trackers remains.

**Closed by josteink** 2023-02-27 07:45 UTC
