### ISSUE TITLE
gmail.get.selected_emails_data() returns wrong emails

### ISSUE THREAD

**Issue by scottwrobinson** [KartikTalwar/gmail.js#417] opened 2017-08-08 20:24 UTC
I recently noticed when `gmail.get.selected_emails_data()` is called (and emails are selected) the wrong emails are returned. When viewing the "Primary" inbox tab, it seems to be returning emails from either "Social" or "Promotions" of the same index number.

Tried to debug a little and it seems `gmail.helper.get.visible_emails_pre()` is returning this URL:

`https://mail.google.com/mail/u/0/?ui=2&ik=b92f69409f&rid=undefined&view=tl&num=120&rt=1&start=NaN&sstart=NaN&search=inbox`

Requests to this URL seems to be returning emails from the "Social" and "Promotions" tabs.

Could the `rid=undefined` and `start=NaN&sstart=NaN` be causing the problem? Let me know what info you need from me to help resolve the issue. Thanks!

**Comment by scottwrobinson** [comment] 2017-08-09 03:25
Quick update:

After spying on Gmail's XHR requests I tried some different parameters in the request URL and it seems that I get the correct emails with `search=mbox` instead of `search=inbox`. The parameters `rid`, `start`, and `sstart` didn't seem to have an affect on returning the correct emails.

Could the fix be as easy as replacing

`url += "&search=" + "inbox";`

with

`url += "&search=" + "mbox";`

at [this line](https://github.com/KartikTalwar/gmail.js/blob/f532bae2841111216bbe221a2334e2f40cbecc14/src/gmail.js#L1740), or is it more complicated than that?

Thanks!

**Comment by josteink** [comment] 2017-08-09 06:31
> at this line, or is it more complicated than that?

It might be that simple, or it might be more complicated :)

It's hard to tell without doing some more testing. I for one don't use these different modes with "Primary", "Social" and what not. I just use it in the "classic" mode where you have an inbox and that is all.

We'd need to make sure your changes works properly across these different setups, and preferably also across regular Gmail accounts vs Google Apps/GSuite accounts.

Right now I'm a little short on time, but if you can assist with testing, outline what you've tested and prepare a PR, it will make it significantly easier for me to get these changes through.

**Comment by scottwrobinson** [comment] 2017-08-09 13:17
I'll test as many setups as I can. Ideas on different configurations to test are welcome (aside from regular Gmail accounts, GSuite accounts, etc). Thanks!

**Comment by josteink** [comment] 2017-08-09 15:07
Some suggestions:

- Classic inbox vs "new" inbox. 
- Testing on page 2 or 3. 
- Testing on labels/folders or searches. 

I think that should be considered extensive enough.

**Comment by josteink** [comment] 2017-08-20 10:51
Any news so far? And conclusive findings?

**Comment by scottwrobinson** [comment] 2017-08-20 18:03
Not yet. Everything seemed to work on my end in all of the test cases, but I had some reports from people that it didn't work for them. Still haven't been able to find out why it works for me but not them

**Comment by scottwrobinson** [comment] 2017-08-23 20:43
Took some more time to look in to this. Looks like [this merged PR](https://github.com/KartikTalwar/gmail.js/commit/485f812c755ea0f8316f7c2ee9bbdbd3953ee8c6) is what broke it for me. Apparently the change was made to accommodate enterprise accounts. For me, using "mbox" works on both normal Gmail accounts and enterprise accounts... :man_shrugging: 

Would love to hear if anyone else has had a chance to test this. Thanks!

**Comment by josteink** [comment] 2017-08-24 05:32
Great digging, Scott. I really appreciate it.

 @Banjerr: Do you have any input/insights into why we are seeing different values for this parameter, or how we can establish what is the best/correct value?

Will we have to do some extra runtime-detection?

**Comment by Banjerr** [comment] 2017-08-24 12:40
very interesting.

@josteink: It's been 3-4 months since I've worked on the project that is utilizing this lib, but I do remember getting incorrect results using "mbox" instead of "inbox". When I get some free time I'll try to dig in and see what was going on. 

Had a couple of minutes this morning, so did a little digging. I keep seeing "mbox" being referred to as a format for emails in an inbox, perhaps some kind of authentication stuff coming into play here? 
https://developers.google.com/admin-sdk/email-audit/
http://en.wikipedia.org/wiki/Mbox

**Comment by josteink** [comment] 2017-09-26 19:50
mbox is a unix plain-text file-format for local mail-agents like [pine](https://en.wikipedia.org/wiki/Pine_%28email_client%29) and [mutt](https://en.wikipedia.org/wiki/Mutt_(email_client)) to organize email.

It's an interesting theory, but I'm absolutely positive that it is not related to anything happening in the Gmail web front-end.

@scottwrobinson: Sorry about the hold up. If you're still around...

Based on @Banjerr's PR you linked to, the comment says:

> replacing query param "mbox" (for enterprise gmail account, apparently) with "inbox"

If we can determine whether we are a enterprise/apps-account or regular gmail account, we should use that to determine the best value.

It seems, we should use "inbox" for enterprise accounts and "mbox" for regular gmail accounts.

Could bother preparing a PR with those changes, and I will do some testing on my end. if everything works here for me too, I'd be happy to merge.

(And if it causes regressions, we'll just take it from there)

**Comment by Banjerr** [comment] 2017-09-26 19:54
@josteink for what its worth, my particular usage with this package was solely with enterprise/apps-account inboxes 👍

**Comment by josteink** [comment] 2017-09-27 19:26
@Banjerr Great.

Based on that feedback, I'd say it's all in your hands now @scottwrobinson. I'll try to be swift and efficient with reviewing and testing :)

**Comment by josteink** [comment] 2017-10-23 07:17
So if @scottwrobinson isn't around to complete this one (despite being the original reporter), I guess I can try to help expedite matters.

My simple proposal for a "enterprise-check" is simply to see if `api.get.user_email()` ends in `"@gmail.com"` or not, and if it doesn't, it's an enterprise-account.

Any objections?

**Comment by josteink** [comment] 2017-11-06 07:07
> My simple proposal for a "enterprise-check" is simply to see if api.get.user_email() ends in "@gmail.com" or not, and if it doesn't, it's an enterprise-account.

It seems we already had this check in `api.check.is_google_apps_user()` and it was implemented just like I was naively going to do it. Guess that's good enough then.

(Internally it doesn't seem to be used for anything yet though.)

I've made some changes based on that, tested and can't see it doing any *harm* at least. Hopefully this should be the end of the story. Closing.

Please re-open if this is still an issue.

**Closed by josteink** 2017-11-06 07:07 UTC

**Comment by scottwrobinson** [comment] 2017-11-14 17:01
Hi @josteink, sorry for not getting back to you. I finally had some time to get back to the project that uses this. I tested your fix and unfortunately it does not work for me. It works fine for "@gmail.com" addresses, but not my enterprise Gmail account with a custom domain name.

Using "search=mbox" works for both my "@gmail.com" account and enterprise account. I'll see if I can get some of my beta testers to give me feedback on this and get a larger sample size.

Thanks for your help on this.

**Comment by josteink** [comment] 2017-11-16 06:17
Hey Scott.

Glad to hear you're back. Sorry to hear it didn't work out. (And good I didn't *push* that as a new NPM-package too)

Let me know what your findings are, and we'll try to get this worked out.
