### ISSUE TITLE
Cannot use get.email_data() in #label or #search.

### ISSUE THREAD

**Issue by dft034** [KartikTalwar/gmail.js#272] opened 2016-06-13 16:05 UTC
I can't use get.email_data() ( or get.displayed_email_data() ) in #label or #search, but only when I arrive from #inbox. The function give me nothing.

How can I have the same result in #label and #search ?

Thanks

**Comment by josteink** [comment] 2017-02-10 20:12
Sorry about the extremely slow response.

With the current version I cannot reproduce this issue, so I'm closing it for the time being,

If you after trying the latest version still feel this is an issue which needs to be resolved, please re-open this issue and post your updated findings.

**Closed by josteink** 2017-02-10 20:12 UTC
