### ISSUE TITLE
Deleted emails get parsed

### ISSUE THREAD

**Issue by ghost** [KartikTalwar/gmail.js#41] opened 2014-03-06 13:56 UTC
Hi,

In a context of threaded emails, you can delete specific emails and thus they get removed from that thread.

However, when using `gmail.get.email_data()`, all emails are considered, including the deleted ones.
That may be a good thing when it comes to handling all emails of a thread regardless of their deletion state.

But when it comes to actually parsing what's currently _here_ on the interface, it's a problem.

I thought it could be an option, to ask for emails including or excluding the deleted ones.
## 

In the process, I guess that would be a separate issue but as it's about deletion...
Is it / would it be possible to observe deletion events on individual emails, not entire threads?

Thanks. (:

**Comment by josteink** [comment] 2017-02-12 11:12
For API-usage wise, this bug can at this point be considered a duplicate of #43 functionally speaking. As such, I'm closing it.

**Closed by josteink** 2017-02-12 11:12 UTC
Labels: bug
