### ISSUE TITLE
get.email_source() doesn't work

### ISSUE THREAD

**Issue by mtourne** [KartikTalwar/gmail.js#357] opened 2016-12-15 22:50 UTC
last gmail.js loaded in Chrome via the extension boilerplaite code.

In the network pane the GET just shows as (failed) no HTTP error code or anything.

Is this a limitation ?

**Comment by michi88** [comment] 2016-12-15 23:15
Hmm that is strange. It's not working for me too. This however does work:

`gmail.get.email_source_async(gmail.get.email_id(), function(email_source){console.log(email_source)})`

Can you confirm that this works?

**Comment by mtourne** [comment] 2016-12-15 23:25
Yes it does! I'll use this for now, thanks for the help

**Comment by michi88** [comment] 2016-12-15 23:47
Strange, I can confirm it only works when `async: true` is set in the jQuery request config.

Maybe we should deprecate `email_source` as we shouldn't be using sync requests anyway.

`jquery.js:8561 Synchronous XMLHttpRequest on the main thread is deprecated because of its detrimental effects to the end user's experience. For more help, check https://xhr.spec.whatwg.org/.`

**Comment by josteink** [comment] 2016-12-16 06:14
We could deprecate it, but that would be a breaking change.

What would be the best/most graceful manner to do that? An empty function which throws a descriptive error inside?

**Comment by michi88** [comment] 2016-12-16 13:29
Yes I think so. I don't see another option unfortunately. Unless we can still make it work with `async: true` but I haven't been able to do that.

**Comment by josteink** [comment] 2016-12-16 14:47
Modern browsers support async/await don't they?

If we could wrap the async call in a promise which we await, could we pull it off? Any opinion?

**Comment by michi88** [comment] 2016-12-16 20:18
Correct me if I'm wrong but I don't think it's possible to convert this synchronous function call to do any async operations and have it return a value. BTW, never used async/await before so did some investigating ([this helped](https://medium.com/@bluepnume/learn-about-promises-before-you-start-using-async-await-eb148164a9c8#.cegd3owuq)) but it's just syntactic sugar for wrapping promises. Consider the following:

```js
var asyncRequest = function(url){
    var promise = new Promise(function(resolve, reject){
        // making the request...
        setTimeout(function(){
            resolve('some email_source data');
        }, 1000);
    });
    return promise;
};

var email_source = async function (url){
    var data = await asyncRequest(url);
    console.log(data);  // <-- will be 'some email_source data'
    return data
}
var data = email_source('http://google.com/.....');
console.log(data);  // <-- will be a promise as the 'async' keyword will wrap the result in a promise if no promise is returned

// all this is just syntactic sugar for wrapping promises like so:
var email_source = function (url){
    return new Promise(function(resolve, reject){
        asyncRequest(url).then(function(data){
            console.log(data);  // <-- will be 'some email_source data'
            resolve(data);
        });
    })};

// same result...
var data = email_source('http://google.com/.....');
console.log(data);
```

Anyway, it's just only possible to return a promise or call a callback function. Which both is not an option regarding backward compatibility.

Maybe we should give it one more go on making it work with `async:false` and if we can't fix it deprecate it by throwing an error as it is broken now already. Without a fix it wouldn't make a difference for the library user (except for understanding that they can/should use `email_source_async`).

**Comment by michi88** [comment] 2016-12-16 21:49
What really is a mystery to me is that
```js
    api.get.visible_emails = function() {
        var url = api.helper.get.visible_emails_pre();
        var get_data = api.tools.make_request(url);
        var emails = api.helper.get.visible_emails_post(get_data);

        return emails;
    };
```
works (also using the synchronous `make_request` call) and `email_source` doesn't....

The browser just blocks the request. It would make sense if `visible_emails` wouldn't work either but it does...

Out of ideas here...

**Comment by josteink** [comment] 2016-12-19 06:17
I suspect this may be due to some technicalities with `email_source()` ending up in a HTTP 301/302 leading to another domain while `visible_emails()` don't(?), but I'll be the first to admit that at this point, this is pure speculation.

**Comment by michi88** [comment] 2016-12-19 16:44
Yeah, the strange thing is that the browser blocks the call, it never ends up going to Gmail servers.

Whereas when using `async=true` the browser doesn't block it. I suspected that chrome was just not allowing the sync requests (on the main thread) anymore but that seems not to be the case as `visible_emails` does work.

**Comment by josteink** [comment] 2016-12-19 16:47
I think async internally uses JSONP instead of regular XHR JSON. That might actually explain things.

At least sounds like a plausible theory.

**Comment by josteink** [comment] 2016-12-19 16:59
And if that's so, this may be a bug we can't fix. In that case... deprecation looks like the only option.

I'm ok with that.

**Comment by michi88** [comment] 2016-12-19 17:19
We're not dealing with JSON at all for these calls.

I've tried to set the `dataType: "text"` also in the `make_request` method (as this is set in the `make_request_async` [method](https://github.com/KartikTalwar/gmail.js/blob/master/src/gmail.js#L1573)) but the result was the same.

Also see: https://learn.jquery.com/ajax/working-with-jsonp/

**Comment by josteink** [comment] 2017-01-05 09:30
Just as an update, I'm still OK and in favour of deprecating this API.

I won't have time to do this cleanly until in a few weeks. If someone else shoves in a PR before that time, I'll be glad to review and merge though.

Things which should ideally be included are the following:

* Replacing method in gmail.js with warning/error.
* Removal of method type-signature from gmail.d.ts.
* Removal from documentation in README.md.
* Update to changelog.

**Comment by michi88** [comment] 2017-01-05 13:34
I'll do it in the coming days!

**Comment by josteink** [comment] 2017-02-10 19:03
@michi88 Since we agreed that the proper fix for `api.get.email_source_async` was rewriting the code to use plain XHR instead of jquery, I guess you're free to deprecate this function at your own leisure. You still on it?

That's it folks. This function is now on its way obsoletion. Please migrate to the async-version instead.

@michi88 Feel free to close this issue once done!

**Comment by josteink** [comment] 2017-09-24 10:27
Warning added. Closing issue.

**Closed by josteink** 2017-09-24 10:27 UTC
Labels: bug, wontfix
