### ISSUE TITLE
Unable to get attachments_details in gmail.get.email_data (gmail.get.email_data_async)

### ISSUE THREAD

**Issue by Capo93** [KartikTalwar/gmail.js#505] opened 2018-07-26 09:55 UTC
Hi,
When I try to get the email content using `gmail.get.email_data` (or `gmail.get.email_data_async`) some email not included attachments data.

I get in `attachments` array the name of the attachements but `attachments_details` is NULL.

<img width="322" alt="schermata 2018-07-26 alle 11 51 57" src="https://user-images.githubusercontent.com/9554023/43255526-59af1c5e-90ca-11e8-95f4-85dc6da73f2b.png">

Module version: 0.7.6

Any assistance would be greatly appreciated.

Best,
Nicola

**Comment by josteink** [comment] 2018-07-27 20:08
It’s a known issue. We don’t know why. 

Either way, I would recommend using latest version when reporting bugs 🙂

**Comment by josteink** [comment] 2018-07-28 09:52
Closing this issue as a duplicate of: https://github.com/KartikTalwar/gmail.js/issues/461,

**Closed by josteink** 2018-07-28 09:52 UTC

**Comment by Capo93** [comment] 2018-07-30 09:31
I use this work around:
I use `gmail.dom.email(id).attachments()` to get the attachments info of the current email (this work with single email visualization).
In thread visualization I use this code to esplode the thread:
`if ( $('#\\:2m').length ) {`
`   $('#\\:2m').click();`
`}`
and after `gmail.dom.email([for each ids]).attachments()` for each threads id to get all attachments.
