### ISSUE TITLE
Observer for poll not working

### ISSUE THREAD

**Issue by bdag** [KartikTalwar/gmail.js#161] opened 2015-03-27 20:54 UTC
Simply pulling from the Readme example, the following will never fire:

gmail.observe.on("poll", function(url, body, data, xhr) {
  console.log("url:", url, 'body', body, 'data', data, 'xhr', xhr);
});

**Comment by KartikTalwar** [comment] 2015-04-03 21:13
hello @bdag is this still an issue? I'm testing it on my personal gmail and google apps account and this seems to be triggering fine for me

**Comment by josteink** [comment] 2017-02-18 20:03
Not able to reproduce on current builds, so closing it.

Please re-open if you still have something you need resolved.

**Closed by josteink** 2017-02-18 20:03 UTC
