### ISSUE TITLE
Observer events don't trigger when expanding past conversation emails

### ISSUE THREAD

**Issue by shahidt** [KartikTalwar/gmail.js#249] opened 2016-04-12 10:53 UTC
Let's say there are 7-8 replies in an email conversation thread. I can click on the grey area to expand a past email in that thread, but there is no observer events triggering when I do so. I set 'on' and 'after' observer events for everything available, but none of them triggered when I open a past hidden email, within a conversation.

What even is ideally supposed to trigger here.

**Comment by brentkelly** [comment] 2016-04-20 00:54
If you have a `view_thread` observer bound, then you can bind a `view_email` observer which will fire when each individual email is clicked on.

There is no observer for when you click the 'show hidden' which expands the thread to show the rest of the conversation - but when the individual emails are expanded to read the `view_email` observer should fire fine (does for me).

**Comment by shahidt** [comment] 2016-04-20 13:33
I am not sure how to reproduce, but I think having the after() observer on certain events prevents some others from working. In my case, I changed all my observers to on() and the problem went away.

**Comment by josteink** [comment] 2017-02-10 20:27
This seems like a duplicate of this issue: https://github.com/KartikTalwar/gmail.js/issues/254 (or the other way around really, but that's life for you).

Either way I'm closing this one. If you still experience this issue on the latest version, please comment on the other issue which is still marked open.

**Closed** 2017-02-10 20:27 UTC
Labels: duplicate
