### ISSUE TITLE
GLOBALS is not available on dedicated-thread page

### ISSUE THREAD

**Issue by onassar** [KartikTalwar/gmail.js#174] opened 2015-05-11 18:58 UTC
It seems I can't create a `Gmail` reference on pages like the following:
`https://mail.google.com/mail/u/0/?ui=2&view=btop&ver=dqujp3h61mgd&search=inbox&th=14d424827ebef4cb&cvid=1`  
You can access your own URLs by heading to your gmail and pressing Command+Click on one of your messages

Looks like the `GLOBALS` object doesn't exist here
Is there a way around this that you've run into?

**Comment by rbpasker** [comment] 2015-11-12 22:11
having the same problem. any ideas here?

Error in event handler for extension.onRequest: TypeError: Cannot read property 'GLOBALS' of null

**Comment by rbpasker** [comment] 2015-11-13 23:07
ok, i figured out what the problem is. you can't put gmail.js in a content page. it has to be injected into the gmail page itself: https://github.com/KartikTalwar/gmail.js/issues/36#issuecomment-36417505

**Comment by josteink** [comment] 2017-02-11 12:30
Seems like this one is solved a long time ago. Closing.

**Closed by josteink** 2017-02-11 12:30 UTC

**Comment by vvass** [comment] 2017-06-09 13:30
Wow this was so helpful. rbpasker comment is exactly what I was looking for! If you don't understand, all you need to do is see how content.js is loading js files in the gmail-chrome-extension-boilerplate project. I put all my contents in a load.js file and used content_sripts to load it.
` "content_scripts": [
    {
      "matches": ["https://*.google.com/*"],
      "js": [ "load.js"]
    }
  ],`

Then it shows up in the main gmail page.
