### ISSUE TITLE
email_view not triggered

### ISSUE THREAD

**Issue by dariospadoni** [KartikTalwar/gmail.js#304] opened 2016-09-13 11:55 UTC
Hello
I'm having troubles while trying to listening to the email_view event on the thread view: this event does not fire and I can't detect when the user clicked on an email of the conversation. My code is pretty straightforward:

```
    var gmail = new Gmail();

    gmail.observe.on('view_thread', function(obj) {
        console.log('view_thread', obj);
    });

        // now we have access to the sub observers view_email and load_email_menu
    gmail.observe.on('view_email', function(obj) {
        console.log('view_email', obj);
    });
```

but I can't see any `view_email` logged. I also tried with custom listener (see code below) by listening to insertion of 'h7' classes element but again, no luck. Am I doing anything wrong? 

```
gmail.observe.register('thread_email_opened', {
      class: 'h7'
});
gmail.observe.on('thread_email_opened', function(match) {
      console.log('thread_email_opened',match);
});
```

**Comment by JerryBels** [comment] 2016-09-25 17:03
Maybe you're trying to execute your code too early. Have you followed the boilerplate example provided ? You need to wait for the document and for Gmail to finish loading before executing your code. I just tried the same code you have in my extension, no problem at all.

**Comment by michi88** [comment] 2016-11-23 01:35
@dariospadoni Can you check if your code works if you first wait for the `gmail.observe.on("load")` event before registering the other events? Also see: https://github.com/KartikTalwar/gmail.js/issues/336

**Comment by ConnGator** [comment] 2017-01-12 16:03
I am having (almost) the same problem where my email observations stop firing after a while.  My code is very similar to the boilerplate:

var main = function()
{
  gmail = new Gmail(); 
  window.addEventListener("message", receiveMessage, false);

  gmail.observe.on("load", function()
  {
    currentMessageId = null;

    gmail.observe.on("view_thread", function()
    {
      console.log('Viewing thread currentMessageId ' + currentMessageId);

      gmail.observe.on("view_email", function(curr)
      {
        currentMessageId = curr.id;
        console.log('Viewing email ID ' + currentMessageId);
      });
    });
  });
}

It works for a while, but if I expand/collapse messages enough times it stops firing.

Any ideas?

**Comment by JerryBels** [comment] 2017-01-14 19:42
Maybe (really not sure about this) you're declaring too much events observers ? Unregistering some of them could help ?

**Comment by ConnGator** [comment] 2017-01-16 15:38
I am pretty sure I need those observers to when the thread or message changes.

**Comment by JerryBels** [comment] 2017-01-16 15:50
I guess you're right. What made me think so is, you're registering a new "view_email" event for each opened thread. I use these without any problem by defining them one above the other : 

    gmail.observe.on('view_thread', function(obj) {
        // console.log('view_thread', obj);
    });
    gmail.observe.on('view_email', function(obj) {
        // console.log('individual email opened', obj);
    });

and also not in a 

    gmail.observe.on("load"

event. `main` function is enough for me, since we're waiting for everything to be fully loaded before calling `main`.

**Comment by ConnGator** [comment] 2017-01-16 16:29
Well, I tried having the view_email not be underneath view_thread, and it worked fine for a while but after opening and closing messages in a thread several time it, too, stopped firing.

Thanks for the suggestion, though.

**Comment by JerryBels** [comment] 2017-01-16 16:35
What I'm doing is that when a mail is opened, I insert something into the html. And if I clic the message to collapse it and expand it again, it doesn't remove my insertions nor does it fire the event again - since it didn't load anything again, that's expected behavior. 

I hope you will find how to get rid of this, good luck

**Comment by josteink** [comment] 2017-02-10 19:49
Considering OP hasn't responded to this issue since filing it, I'm going to assume this is no longer a problem.

Because of that, I'm closing this issue. Please re-open if you still have something you need to resolve.

**Closed by josteink** 2017-02-10 19:49 UTC
