### ISSUE TITLE
Failure to read property GLOBALS when using gmail.dom.email(obj) in a threaded message

### ISSUE THREAD

**Issue by YesThatAllen** [KartikTalwar/gmail.js#450] opened 2018-03-01 04:15 UTC
We've got an app that surfaces information in gmail's web-ui based on the to:/from: or a keyword in the body.

Over the past two months, I've watched it start to fail on threaded messages. The failures did not seem to coincide with changes in our tool, or changes in this repo's gmail.js. I assume it was changes in gmail.

Our tool still works fine on single emails, but fails if there is more than one email in the thread.

the failure shows as:

```
gmail.js:674 api.dom.email called with invalid element/id
VM4905:239 Uncaught TypeError: Cannot read property 'includes' of undefined
    at <anonymous>:239:30
    at Array.forEach (<anonymous>)
    at <anonymous>:238:23
```
the full failure is in this gist.

For quite some time, I was able to solve it by merging in the changes from @hitbits ' PR titled [Fix issues for api.get.visible_emails](https://github.com/KartikTalwar/gmail.js/pull/421)

I'm not the one who built this tool, and if there's someone out there who'd rather get paid to fix this for us (and submit any needed changes to this repo) I'd be open to hearing from you.

**Comment by josteink** [comment] 2018-03-01 07:16
> Over the past two months, I've watched it start to fail on threaded messages.

I'm not able to reproduce this, but I'm only using `api.dom.email` via `api.observe.on("view_email")`.

Can you provide a minimal extension which reproduces this issue, based on for instance on [the boilerplate repo](https://github.com/josteink/gmailjs-node-boilerplate/)?

> For quite some time, I was able to solve it by merging in the changes from @hitbits ' PR titled Fix issues for api.get.visible_emails

Does that mean this workaround is no longer working for you?

I'd love to get that PR merged, but with no feedback from the author to my review questions... It's kind of hard to feel confident you are merging good code.

**Comment by YesThatAllen** [comment] 2018-03-02 22:04
I'm working on getting you answers to your questions. As for the hitbits PR, it was helpful, but I think whatever google changed hurt that code as well.

**Comment by YesThatAllen** [comment] 2018-03-03 20:47
To confirm, the edits from hitbits PR are no longer working here. I'm seeing if there's someone on my team who can help with the boilerplate test (see earlier note about willingness to hire for this job ;-) )

**Comment by YesThatAllen** [comment] 2018-03-03 21:19
for what it's worth, I think this is where we're getting caught up, we get an error on 

`            var email = new gmail.dom.email(obj);`

then fail as we compare our list of `internalusers`

This part of code of our hasn't been changed in two years.

```
    gmail = new Gmail();
    console.log('Hello,', gmail.get.user_email());

    // need this to open_email
    gmail.observe.on('view_thread', function(obj) {
        console.log("viewing thread...");
        createUSerInfoSidebar();
    });

    gmail.observe.after("open_email", function(obj) {
        console.log("opened email...");

        setTimeout(function() {
            var email = new gmail.dom.email(obj);
            console.log("set email.");
            var from = email.from();
            console.log("set from.");
            var lookupEmail = "";
            console.log("set lookup email.");

            if (internalusers.indexOf(from.email) > -1) {
                lookupEmail = to[0].email;
```

**Comment by josteink** [comment] 2018-03-05 07:03
Thanks for the sample.

If we look closely at your code, it seems to me that you use the `open_email`-event to extract the emailID (in `obj` ). Then you use `setTimeout` to yield execution back to Gmail... until you use `new gmail.dom.email(obj)` to try to get a DOM-object for the email. And this is where you say it fails.

The bad news: I have no idea why that fails.

The good news: You are doing more work than you need to, and cleaning that up may also fix your problem. Try changing your code from: 

````javascript
    gmail.observe.after("open_email", function(obj) {
        console.log("opened email...");

        setTimeout(function() {
            var email = new gmail.dom.email(obj);
            /// code here
        });
    });
````

to using the `view_email` event which provides you with a ready-to-use DOM object instead:

````javascript
    gmail.observe.after("view_email", function(email) {
        console.log("opened email...");
        /// code here
    });
````

Let me know if that works any better for you.

**Comment by YesThatAllen** [comment] 2018-03-14 04:26
With this change, our tool doesn't see any email... it's actually beyond my skillset to troubleshoot further. I've asked my team to review, and will follow up when I have more.

**Comment by josteink** [comment] 2018-03-14 06:32
Please note you will (as mentioned in the documentation) still need to subscribe to `view_threads` for `view_email` to work.

Your complete code should look like this:

````javascript
 gmail = new Gmail();
 console.log('Hello,', gmail.get.user_email());

 gmail.observe.on('view_thread', function(obj) {
     console.log("viewing thread...");
     createUSerInfoSidebar();
 });

 gmail.observe.after("view_email", function(email) {
     console.log("opened email...");
     /// code here
});
````

**Comment by evgenyo** [comment] 2018-03-27 05:21
@josteink That did the trick. Thank you for the help.

**Comment by josteink** [comment] 2018-03-27 06:59
Great. I'll consider the issue solved then. Closing!

**Closed by josteink** 2018-03-27 06:59 UTC
