### ISSUE TITLE
"view_email" event fires twice

### ISSUE THREAD

**Issue by kaeevans** [KartikTalwar/gmail.js#778] opened 2024-02-23 19:53 UTC
**Issue:**
"view_email" fires twice when I open an email from the inbox.
I am using the boilerplate code from the [gmailjs-node-boilerplate](https://github.com/josteink/gmailjs-node-boilerplate/) repo.

**Solution tried:**
I followed the debugging instructions in [issue 526](https://github.com/KartikTalwar/gmail.js/issues/526) and confirmed that the "view_email" event-handler is only registered once. The call stack is the same each time "view_email" fires:
<img width="379" alt="IMG_7012" src="https://github.com/KartikTalwar/gmail.js/assets/3758445/04c02c08-422f-4016-82a1-3e16269001fc">

Have you seen this before? Do you know what might be causing it?

**Comment by josteink** [comment] 2024-02-23 21:34
This kind of seems to be a duplicate of https://github.com/KartikTalwar/gmail.js/issues/765.

The `email_view` and `thread_view` events has always been ... not extremely deterministic, due to how Gmail does rendering, pre-rendering etc. And new gmail has made things even more "interesting".

There's no "proper" fix for this yet, and the simplest way to deal with this is simply making your event-handling code idempotent (i.e. triggering the same event multiple times results in the same outcome as triggering it once), as suggested in the linked thread.

Closing this issue, as duplicate.

**Closed by josteink** 2024-02-23 21:34 UTC
